AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0157af9aea2eef346 # Update with a valid AMI ID for your region
      KeyName: Javed-homework1 # Replace with an existing key pair
      Tags:
        - Key: Name
          Value: CloudFormation-EC2
